### ISSUE TITLE
Docker Modules

### ISSUE THREAD

**Issue by chouseknecht** [ansible/proposals#1]
This is the place for discussing the proposed Docker modules. Add suggestions and ideas here.

**Comment by jakemcdermott** [comment]
@chouseknecht

Hey Chris - I'm reading over your proposal for the container module and I'm curious if there are any plans to implement something similar to the _count_ parameter from the current docker module?

As the examples in this proposal indicate, you can certainly start and stop multiple containers using  _with_items_ or _with_sequence_. The indempotence of the count parameter, however, lets you easily scale the number of containers up or down through a single playbook/host variable. 

Having a dedicated module parameter for the container count also means you can use handlers for the change events that are triggered when the number of containers on a host changes unexpectedly between playbook runs.

**Comment by bcoca** [comment]
@jakemcdermott I'm not sure why that is needed since all of that can still be achieved in a `with_` loop.

**Comment by gregdek** [comment]
See new Docker module proposals in detail here:

https://github.com/ansible/proposals/tree/master/docker

Please feel free to comment on the proposals here.

**Comment by ibotty** [comment]
I welcome the addition of sane docker modules! I only looked at the things I tend to need (pulling images, managing container lifecycle) and these look way better! Thank you for cleaning up!

Is there an ETA or some way to help (after the ground work is done)?

**Comment by bcoca** [comment]
As per meeting we are going to accept the proposals, will discuss implementation details on the PRs.
