### ISSUE TITLE
Define variable or fact when debug is set

### ISSUE THREAD

**Issue by jdh239** [ansible/proposals#106]
# Proposal: Define variable or fact when debug is set

*Author*:  jdh239

*Date*: 2018/04/18

- Status: New
- Proposal type: Feature Request

## Motivation
I would like to be able to skip or execute certain tasks based on debug verbosity level.

### Problems
What problems exist that this proposal will solve?
- Problem #1:  meta: end_play when debug level is greater than <#>.  This would allow easier debugging and prevent execution beyond the current point of debugging
- Problem #2:  Allow me to skip/execute specific tasks when debugging.

Probably a lot of other scenarios to use this in, but that is all I have for right now.

## Solution proposal
Set a variable or fact that can be used in conditionals based off of the verbosity level. (ie. ansible-playbook -vv myplay.yml)

meta: end_play
when: verbosity >= 2

or

- name: Sample task
  shell: "Some stuff"
  register: myvar
  when: verbosity >= 3

It would allow more flexibility while debugging.  I can execute my playbook without debugging and have it execute the whole thing, or terminate early with debugging without having to constantly edit my playbook to add meta: end_play statements, etc.

**Comment by sivel** [comment]
This has recently been implemented in https://github.com/ansible/ansible/pull/38231 and will appear in the 2.6 release.

The var will be `ansible_verbosity`

**Comment by jdh239** [comment]
Sweet!  Thanks!
