### ISSUE TITLE
Please add more choices for parameters (nxos_logging_module)

### ISSUE THREAD

**Issue by dhakalanis** [ansible/proposals#107]
# Proposal: Please add more choices for parameters (nxos_logging_module)

*Author*: Anis Dhakal (https://api.github.com/users/dhakalanis)

*Date*: 04/18/2018 (mm/dd/yy)

- Status: New
- Proposal type:  Add  more choices to parameters. 
- Targeted Release: 2.6 +
- Associated PR: 
- Estimated time to implement: 1 week

## Motivation
Need a way to send syslogs to remote destination.

### Problems
Nexus devices should be able to send syslogs to remote destination. Since the feature is available on CLI, my request is to have similar on Ansible nxos_logging_module too.

## Solution proposal
Please include all the choices for teh parameter. Details are below:
http://docs.ansible.com/ansible/latest/modules/nxos_logging_module.html
Parameter: dest
Choices Currently available:
console
logfile
module
monitor

Proposed new Choices:
  server
  event   
  history 
  ip         
  level    
  message
  persistent
  rate-limit 
  server      
  source-interface 
  timestamp   

Reference from NXOS / exact CLI on the Nexus device:
ANS-SPINE2(config)# logging ?
  console           Set console logging
  event             Interface events
  history           Modifies severity level or size for history table
  ip                IP configuration
  level             Facility parameter for syslog messages
  logfile           Set File logging
  message           Interface events
  module            Set module(linecard) logging
  monitor           Set terminal line(monitor) logging level
  persistent        Set persistent logging
  rate-limit        Enables rate limit for log messages
  server            Enable forwarding to Remote Syslog Server
  source-interface  Enable Source-Interface for Remote Syslog Server
  timestamp         Set logging timestamp granularity

## Dependencies (optional)
N/A

## Testing (optional)
Yes.
For ex : On "parameter" server , please set a server (3.3.3.3) as logging server.
Configure the device to send logs to 3.3.3.3

## Documentation (optional)
Based on above info , please update teh documentation as well . 
http://docs.ansible.com/ansible/latest/modules/nxos_logging_module.html

## Anything else?
I'm relatively new to Ansible and I would like to contribute to Ansible documentation as well. Please share me any details, reference guide to help me contribute.

**Comment by trishnaguha** [comment]
Closing this as it is tracked in https://github.com/ansible/ansible/issues/39101
