### ISSUE TITLE
task notify / handler listen on keyword

### ISSUE THREAD

**Issue by resmo** [ansible/proposals#11]
# Proposal: task notify / handler listen on keyword

Replaces the #8 proposal

*Author*: René Moser <@resmo>

*Date*: 2016/04/19

- Status: New
- Proposal type: core design
- Targeted Release: 2.2
- Associated PR: N/A

## Motivation
Based on the discussion and comments of #8 I reworked the proposal and avoid using the words publish/subscribe as different people associate different things with them.

This proposal extends the current notify handlers functionality. In addition to notify a handler by its name,  the proposal allows to notify a keyword which does not correspond to a handlers name. 

Handlers listen to this keyword: `listen: <keyword>` will be notified and executed. If no handler listen to the keyword, no error should occur. 

The scope is limited on play like the current `notify: <handler_name>`. 

### Problems

In the current `notify: <handler_name>` functionality, you need to know the handler names to be notified. But there are some use cases, especially in roles specified as dependency, in which you can not know the handler name or know if there are any handlers, one handler or a few handlers to be notified.

## Use Case - Role and role dependency

We have a simple playbook using roles configuring services (httpd, postfix)

~~~yaml
---
- hosts: web
  roles:
    - httpd

- hosts: mail
  roles:
    - postfix
~~~

As those services use SSL, we have a simple common ssl role managing all SSL certs/keys:

~~~yaml
# role ssl
# ssl/tasks/main.yml
---
- name: include OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: copy SSL certs defined
  copy: src={{ item }} dest={{ ssl_certs_path }}/
  with_items: ssl_certs

- name: copy SSL keys defined
  copy: src={{ item }} dest={{ ssl_keys_path }}/
  with_items: ssl_keys
~~~

In roles depending on SSL certs (e.g. httpd, postix) you configured the SSL role as dependency:

~~~yaml
# meta/main.yml
---
dependencies:
  - ssl
~~~

In the tasks of the roles httpd,postifx we configued the SSL certs in templates, as we can be sure, they are available and notify our handlers to restart the services as usual:

~~~yaml
# httpd/tasks/main.yml
- name: configure service with ssl 
  template: ...
  notify: restart httpd
~~~

Role httpd handlers:

~~~yaml
# httpd/handler/main.yml
---
- name: restart httpd
  service: name=httpd state=restarted
~~~

Same for our postfix role and notify our postfix service handler:

~~~yaml
# postifx/tasks/main.yml
- name: configure service with ssl 
  template: ...
  notify: restart postifx
~~~

Role postifx handlers:
~~~yaml
# postifx/handler/main.yml
---
- name: restart postfix
  service: name=postfix state=restarted
~~~

Pretty straight forward.

As you know, certs are only valid for some time and we need to replace them once in a while.  

Now the question is, how can we restart all services using SSL to make use of the new cert by notifying all handles in the roles depending on the ssl role?

Add the notify handler names to the task would work, right?:

~~~yaml
- name: copy SSL certs defined
  copy: src={{ item }} dest={{ ssl_certs_path }}/
  with_items: ssl_certs
  notify:
    - restart httpd
    - restart postfix
    - restart xyz
~~~

Yes, this would work but remember, the SSL role is a common role and may be on galaxy. To keep it common you usually would not notify a handler not specified in this SSL role. 

However there would be a few solutions to that problem with current ansible functionality but they make things unwanted complicate and regarding roles on galaxy, support for roles on galaxy is not as simple as it could.

## Solution proposal

Coming back to our use case, we would add a notify to the tasks in our SSL role but just using a keyword `event_ssl_changed` not associated with a handler name.

~~~yaml
# role ssl
# ssl/tasks/main.yml
---
- name: include OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: copy SSL certs defined
  copy: src={{ item }} dest={{ ssl_certs_path }}/
  with_items: ssl_certs
  notify: event_ssl_changed

- name: copy SSL keys defined
  copy: src={{ item }} dest={{ ssl_keys_path }}/
  with_items: ssl_keys
  notify: event_ssl_changed
~~~

In roles depending on SSL certs (e.g. httpd, postix) you configured the SSL role as dependency like before:

~~~yaml
# meta/main.yml
---
dependencies:
  - ssl
~~~

In the role httpd handlers main.yml we add a new param `listen: <keyword>` to listen for the notified keyword.

~~~yaml
# httpd/handler/main.yml
---
- name: restart httpd
  service: name=httpd state=restarted
  listen: event_ssl_changed
~~~

The same in our postifx role.

~~~yaml
# postifx/handler/main.yml
---
- name: restart postfix
  service: name=postfix state=restarted
  listen: event_ssl_changed
~~~

To show the solution in a simplified way in a playbook task play:

~~~yaml
- hosts: webservers
  tasks:
    - name: copy SSL certs defined
      copy: src={{ item }} dest={{ ssl_certs_path }}/
      with_items: ssl_certs
      notify: ssl_certs_changed

  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
      listen: ssl_certs_changed

    - name: restart postfix
      service: name=postifx state=restarted
      listen: ssl_certs_changed
~~~

**Comment by jimi-c** [comment]
Closing, as this feature has been implemented.
