### ISSUE TITLE
add "apt-get clean" functionality to apt module

### ISSUE THREAD

**Issue by bhmayor** [ansible/proposals#112]
# Proposal: Modification of apt module to include "apt-get clean" functionality

*Author*: Blake

*Date*: 07 MAY 2018

- Status: New
- Proposal type: add the functionality described in the subject of this request
- Targeted Release: next forthcoming release
- Estimated time to implement: depends on how many programmers are working on it and how long regression testing takes.

## Motivation
This module stands in the absence of proffering the suggested capability.

### Problems
What problems exist that this proposal will solve?

The apt module has not the manner by which to execute a task not unsimilar to "apt-get clean".

## Solution proposal
Writing code to add this capability will resolve the issue.

## Dependencies (optional)

None.

## Testing (optional)

This function should of course be fully tested prior to being made available, I agree.

## Documentation (optional)

Yes, document this.

## Anything else?
N/A

**Comment by webknjaz** [comment]
Hi @bhmayor,

It doesn't look like a huge architectural change, thus it doesn't need to be a widely discussed proposal in this repo.
Instead, you may go ahead and create a PR, it shouldn't be had/much to change there in the existing codebase.

Oh.. and it looks there's already a feature request for this: ansible/ansible#38920.
So I'm going to close this issue and encourage you to move conversation there or create a PR.

Have a nice day :)

**Comment by bhmayor** [comment]
Why was this closed?

**Comment by amenonsen** [comment]
@bhmayor the explanation above seems quite clear.

**Comment by bhmayor** [comment]
amenonsen,

Yeah, clear as mud - right! Let me suggest to you that uh, well, "reading really is fundamental"!

#38920 was closed because this issue exists and this issue was closed because #38920 exists. So, like now both of them are closed and nothing will happen. So, why was this was closed is a totally reasonable and appropriate question.

Then this dude webknjaz said to create a PR, but does anyone like really know what a PR is? Maybe he means I should go to Puerto Rico? I don't know. Whatever he means, I don't want the issue closed I want it to be debated and perhaps taken on as something the developers see value in and adding to Ansible. Get it?

Thanks,

Blake

**Comment by amenonsen** [comment]
> "reading really is fundamental"!

Yes, I agree completely. And:

> #38920 was closed because this issue exists

#38920 isn't closed.

**Comment by willthames** [comment]
@bhmayor PR is a fundamental concept of GitHub, it's a Pull Request, a means of discussing and reviewing improvements.

The community documentation on how to file issues and pull requests is at https://docs.ansible.com/ansible/latest/community/how_can_I_help.html#file-and-verify-issues. As an existing pull request exists for this issue, you can watch that PR or add any additional information that might help improve the pull request.

This repository is for discussing architectural changes and concepts, rather than small feature improvements to a module.

**Comment by webknjaz** [comment]
@bhmayor

Hey Blake,

I'm sorry, I didn't check whether you're well-familiar with GitHub. @willthames is right, for GitHub/GitLab/Bitbucket users it is common to use PR for Pull Request (GitLabbers call it a Merge Request), which has been basically invented by GitHub probably around 7-8 years ago, it's a way/process for sending your patches to some project which is hosted in such code hostings.

I believe that this GitHub's doc can help you understand it better: https://help.github.com/categories/collaborating-with-issues-and-pull-requests/.

But long story short: hit "Fork" button (top right @ https://github.com/ansible/ansible page), create a branch from `devel` in your own fork which you'll have then (https://github.com/bhmayor/ansible). Push commits to that branch in your copy of the project. Then go to https://github.com/ansible/ansible/compare/devel...bhmayor:?expand=1 and select the branch you have just created, fill in the title and pre-filled template. As a result, you'll get an issue-like page with a tab for viewing diff, where people will comment/review your code. If you're requested to change something, just push new commits to the same branch. Finally, when we are ready to accept the patch, we'll hit "Merge" button and the code will land into `devel`.

You are claiming that ansible/ansible#38920 is closed, but nobody ever closed it. You likely noticed `@webknjaz referenced this issue in ansible/proposals on May 11` in the bottom and there's a subline mentioning *this* (ansible/proposals#112) issue name and *this* issue status (Closed). To see the status of ansible/ansible#38920 go there and see green `Open` label right under issue title.

I hope this all doesn't look as cryptic to you now and you'll be able to proceed with the next steps :)
Have a nice day!
