### ISSUE TITLE
Expose command-line tags to the playbook

### ISSUE THREAD

**Issue by dagwieers** [ansible/proposals#114]
# Proposal: export-tags

*Author*: Dag Wieers <@dagwieers> IRC: dag

*Date*: 2018-05-14

- Status: New
- Proposal type: core
- Targeted Release: 2.7
- Associated PR: <link to GH PR in ansible/proposals if PR was submitted>
- Estimated time to implement: hours

## Motivation
The provided tags can influence how the playbook behaves or is executed. As a result it is useful to have this information available.

### Problems
We send out mails on failure (callback plugin) and send out a mail after successful execution of a complex playbook (mail module), but both do not report exactly with what tags the playbook was executed while this is a crucial part of understanding what has happened.

Exposing this information to the playbook makes it possible to report this information as part of the mail body together with other relevant information.

## Solution proposal
- Expose the used tags as `ansible_tags`

## Testing (optional)
Tests are not optional

## Documentation (optional)
Documentation is not optional.

**Comment by bcoca** [comment]
3 things:
- you already have `ansible_only_tags` and `ansible_skip_tags` to reflect such options
- variables are not normally passed to callbacks
- callbacks already have access to the cli options via `self._options`, when using `CallbackBase`

**Comment by dagwieers** [comment]
Thanks @bcoca

**Comment by dagwieers** [comment]
@bcoca I couldn't find this in the Ansible documentation, maybe I wasn't looking right. Do you know where this is documented ?
