### ISSUE TITLE
Docker - new module to create a swam environment.

### ISSUE THREAD

**Issue by tbouvet** [ansible/proposals#115]
# Proposal: <proposal name>
Add new module to create/update a docker swarm
*Author*: Thierry Bouvet <@tbouvet> IRC: handle (if different)

*Date*: 2018/05/14

- Status: New
- Proposal type: (core design, process, ?) docker
- Targeted Release: 2.6
- Associated PR: https://github.com/ansible/ansible/pull/38280 
- Estimated time to implement: 0 days (it's done by the PR)

## Motivation
The reason is to have an idempotent module to create/update a swarm environment for docker.

### Problems
What problems exist that this proposal will solve?
The only solution to create/update a swarm is to do "by hand". That's mean, you can only use shell/command module. So it's not idempotent.

## Solution proposal
See https://github.com/ansible/ansible/pull/38280  

## Dependencies (optional)
docker-api

## Testing (optional)
An integration test is done.

## Documentation (optional)
documentation is done.

## Anything else?
If you'd like to add anything else beyond the above required and optional sections, you are welcome to do so.

**Comment by dagwieers** [comment]
I don't think you need to follow the proposal process for creating modules. You can just create a PR with the module, docs and tests, then find someone doing the review and eventually merge.

**Comment by tbouvet** [comment]
Thank you for your answer. I have done the PR with docs and tests and I'm waiting for someone to do the review. Do you know how to contact someone to do the review ?

**Comment by dagwieers** [comment]
Asking on IRC #ansible-devel usually does the trick, in your case asking the same people that already reviewed helps too. In some cases you can look for authors or contributors to other modules in the same technology-domain (i.e. Docker).

Forming a Docker-related team could be useful to manage Docker-related modules and provide support. And you can cross-review contributions and merge them.

If you really are stuck and nobody is there to help, you can raise it to [the Public Ansible meeting agenda](https://github.com/ansible/community/issues/308) as a last resort.

**Comment by tbouvet** [comment]
Done : https://github.com/ansible/ansible/pull/38280
