### ISSUE TITLE
Ansible should allow extra vars from "non-file" paths

### ISSUE THREAD

**Issue by galund** [ansible/proposals#116]
*Author*: George Lund
*Date*: 2018-05-16

- Status: New
- Estimated time to implement: 2 days?

## Motivation

We store our secrets outside of ansible for historical reasons, and ansible-vault isn't a suitable place for us to keep them right now. We therefore need a secure way to pass secrets into ansible playbooks etc as extra variables.

### Problems

Under ansible 1, we were able to use bash process substitution [http://tldp.org/LDP/abs/html/process-sub.html] to decrypt our secrets and pass them into ansible, approximately as follows:

```
ansible-playbook -e @<(command-to-decrypt-secrets-to-stdout)
```

This no longer works in ansible 2, failing with the following error message:
```
ERROR! Unable to retrieve file contents
Could not find or access '/dev/fd/63'
```

Ansible 2 refuses to recognise the file descriptor that bash has created as a valid pseudo-file from which to read extra variables.

Our current workaround uses temporary files, which is less secure.

## Solution proposal

The existing process followed by `DataLoader._get_file_contents` is too strict. It checks `os.path.isfile`, which is `False` for file descriptors of non-files in process substitution and other named fifo buffers (i.e. you can also get a similar problem by using `mkfifo`).

The `is_file` test could simply be moved into the `except` clause, i.e. be used to help give the user a helpful error message, but not actually prevent ansible from attempting to open the file spec passed in.

Assuming the user _has_ actually passed in something readable does seem more reasonable then attempting to test all the ways that the user might have done that wrong, anyway!

**Comment by agaffney** [comment]
This is something that should probably just be a standard issue and treated as a regression from 1.x. It sounds like you already have a possible implementation, so you should just create a PR.

**Comment by galund** [comment]
Thanks; unfortunately I'm struggling to understand how to set ansible up for running its unit tests, so this is likely to sit in limbo for some time. I'll create an issue and put a link up to my branch, for now.
