### ISSUE TITLE
Specific configuration must override generic configuration

### ISSUE THREAD

**Issue by puriadeb** [ansible/proposals#122]
# Proposal: Specific configuration must override generic configuration

*Author*: Debashis Prusty <debashis.prusty@gmail.com> IRC: handle (if different)

*Date*: 2018/29/06

- Status: New
- Proposal type: core design
- Targeted Release: <future release #, ex. 2.2>
- Associated PR: <link to GH PR in ansible/proposals if PR was submitted>
- Estimated time to implement: <X days, weeks, etc.>

## Motivation
Generic variables defined within the playbook or provided via vars files are applicable for all hosts. But if the user wants some of the generic values (like interface name) to be different for a particular host, then there is no inbuilt mechanism to override that. 

### Problems
What problems exist that this proposal will solve?
- Problem #1 I am doing some network configurations where interface name and IP varies for some hosts. Then I can simply specify those values in host specific file and through configuration change this issue is resolved.
- Problem #2 I have few master nodes selected through polling. The set of master nodes is dynamic. That information is stored in my configuration locally. Now some patch upgrades should be differed on those hosts. Now this particular host specific value prevents those patches being applied on the masters.

In our playbooks we are importing all host specific variables at the end of setting variables section like below.
- name: Including host specific variables from current directory (if exists)
  include_vars: 'host_vars/{{ inventory_hostname }}'
  ignore_errors: yes
roles:
  - h_conf
  - n_conf
  - patch_deploy

## Solution proposal
- Change the variable precedence.
The below should be the precedence list,
...
set_facts / registered vars
role (and include_role) params
include params
**inventory host_vars/* 
playbook host_vars/* 
host facts**
extra vars (always win precedence)
https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

**Comment by drybjed** [comment]
No. This is solvable perfectly fine right now if you use the inventory variables properly. The order of the variables in the inventory is:
- `inventory/group_vars/all/`
- `inventory/group_vars/<group>/`
- `inventory/host_vars/hostname/`
With what you want to do, you can just setup a default layout in `inventory/group_vars/all/` directory, and then override it in specific host directories using the same variable names. They will do exactly what you want, which is override global variables with specific variables.

**Comment by puriadeb** [comment]
@drybjed Not sure if understood the proposed solution. So explaining the problem a bit more.
If I have "myVar=true" defined in vars section of main.yml, how can I overwrite it to "false" by means of some vars file (not commandline). That is without using "--extra-vars".

**Comment by drybjed** [comment]
If we are talking about role variables, don't use `vars/main.yml` file for them. Put the variables in `defaults/main.yml`, in that case they can be easily overriden via Ansible inventory where you can have all/group/host granularity as you please.

Playbook variables are not as flexible, therefore it's best not to use them in this context. I'm not using them at all, and instead rely on role default variables.

**Comment by bcoca** [comment]
https://docs.ansible.com/ansible/latest/reference_appendices/general_precedence.html <= clear 'configuration/settings' precedence rules, variables are part of it  for a good reason and 'specificity' is normally associated with host > play.

The variable precedence (linked and referenced in subject) is orthogonal (it influences value of variable considered in configuration precedence) but does not determine the general precedence.

AS such I'm going to close this as 'completed', though it was unclear at the time, clear documentation has been provided now.
