### ISSUE TITLE
Task retries without until parameter

### ISSUE THREAD

**Issue by barlik** [ansible/proposals#132]
# Proposal: <proposal name>

*Author*: Rastislav Barlik <@barlik>

*Date*: 2018-07-20

- Status: New
- Proposal type: core design
- Targeted release: 2.7
- Associated PR: https://github.com/ansible/ansible/pull/43128
- Estimated time to implement: already done

## Motivation
Make task `retries` simpler and more intuitive. I've recently used URI module to write tens of API calls all of which needed a couple of retries and I've realized that every task has a `register: out` and `until: out is successful` parameters although I don't really need the `out` variable.

### Problems
Task `retries` parameter is silently ignored when `until` parameter is not specified. Until parameter is not always needed so using just `retries` parameter should be enough for some tasks.

What problems exist that this proposal will solve?
- I want to retry a task until it succeeds and don't want to write extra `register` and `until` parameters.

## Solution proposal
Allow to omit `until` parameter from a task and still respect `retries` parameter. The task will be retried specified amount of times until it is successful.

```yaml
    - name: Retry URL call up to five times until we get 200 status code
      uri:
         url: https://httpbin.org/ip
         status_code: 200
      retries: 5
```
The above example looks correct, but at the moment it will only ever run once as `retries` parameter is **silently ignored** because there's no `until` parameter. To make it work as expected we need to add:
```yaml
      register: uri_call
      until: uri_call is successful
```
which seems unnecessary and moreover registers an extra variable that is not needed.

## Testing (optional)
Unit tests to verify expected behaviour.

## Documentation (optional)
The documentation update is needed.

**Comment by dagwieers** [comment]
If it was up to me (see #30957), this would be possible:
```yaml
    until: this is successful
```

**Comment by barlik** [comment]
@dagwieers That's not a bad suggestion. I would still prefer `until: this is successful` to be implicit though.

**Comment by bcoca** [comment]
discussed in IRC meeting and we all agree on proposed feature, comments on implementation in PR incoming.

**Comment by barlik** [comment]
Any updates?

**Comment by s-hertel** [comment]
New attempt: https://github.com/ansible/ansible/pull/76101

**Comment by mkrizek** [comment]
Implemented in https://github.com/ansible/ansible/pull/81531
