### ISSUE TITLE
sftp_executable , scp_executable

### ISSUE THREAD

**Issue by eric-b-hymowitz** [ansible/proposals#138]
# Proposal: sftp_executable , scp_executable

*Author*: Eric B. Hymowitz <@eric-b-hymowitz> 

*Date*: 2018-08-07

- Status: New
- Proposal type: core design
- Targeted release: unknown
- Associated PR: n/a
- Estimated time to implement: unknown

## Motivation
My system uses an outdated version of `openssh` and I cannot update it.  I need to use extra ssh_configuration features with ansible that are not available with the system-standard `ssh` .  I can set the `ansible_ssh_executable` variable to use a different `ssh` program than the system's standard, but I cannot do the same for `scp` and `sftp` .  This results in errors when the system-standard `sftp` / `scp` programs try to use the config file that only works with my updated `ansible_ssh_executable`.

### Problems
My system uses an outdated version of `openssh` and I cannot update it.  I need to use extra ssh_configuration features with ansible that are not available with the system-standard `ssh` .  I can set the `ansible_ssh_executable` variable to use a different `ssh` program than the system's standard, but I cannot do the same for `scp` and `sftp` .  This results in errors when the system-standard `sftp` / `scp` programs try to use the config file that only works with my updated `ansible_ssh_executable`.

## Solution proposal
Analagous to the `ansible_ssh_executable` variable, there should be a `ansible_scp_executable` variable and a `ansible_sftp_executable` variable.

**Comment by Shaps** [comment]
Given the not very big impact of this, I think it could just be a feature request issue, instead of an actual proposals. Proposals are for requests with much bigger impact and scope. 
That said, I have been in a similar situation ( that's why you now can use `ansible_ssh_executable` :) ), so I'd be ok adding those 2 variables.

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/pull/36648
