### ISSUE TITLE
Allow user to break out of pause-prompt

### ISSUE THREAD

**Issue by eric-b-hymowitz** [ansible/proposals#139]
# Proposal: Allow user to break out of pause-prompt

*Author*: Eric B. Hymowitz <@eric-b-hymowitz> 

*Date*: 2018-08-07

- Status: New
- Proposal type: core design
- Targeted release: unknown
- Associated PR: n/a
- Estimated time to implement: unknown

## Motivation
A pause potentially allows the user to wait for a specific event to occur before allowing ansible to continue.  A pause configured with a specific time allows the user to abort a playbook.  A pause with no specific time, waiting instead for user to hit return, should also allow the user to abort a playbook.

### Problems
A pause potentially allows the user to wait for a specific event to occur before allowing ansible to continue.  If the event does not happen, or some other troubleshooting is needed, the user cannot break out of the pause module.  His only option is to hit RETURN and continue the playbook.

A pause that has a specific time attached will allow the user to hit Control-C and then A to abort the playbook.  The untimed pause does not offer such an option; Control-C has no effect.

The untimed pause should allow the same option to break out of a playbook that the timed pause does.

## Solution proposal
Activate the Control-C to allow a user to abort a playbook, rather than the current behavior of trapping the Control-C and ignoring it.

**Comment by agaffney** [comment]
This request is extremely limited in scope, which means that it should probably just be a standard feature request in `ansible/ansible` rather than a proposal.

**Comment by eric-b-hymowitz** [comment]
I’m not sure I understand what you’re saying.

I started at

https://docs.ansible.com/ansible/latest/community/reporting_bugs_and_features.html#requesting-a-feature

... and it says ...

The next best way of getting a feature into Ansible is to submit a proposal through the Ansible proposal process<https://github.com/ansible/proposals>.

...which links me to

https://github.com/ansible/proposals

What are you suggesting I do?

--EbH

**Comment by sivel** [comment]
Proposals are meant to be for discussions around large impacting changes to the way Ansible functions or will function.  For small feature needs for existing functionality, please open a feature idea issue at https://github.com/ansible/ansible/issues/new?template=feature_request.md
