### ISSUE TITLE
Introduce a new pattern for modules; "audit" modules

### ISSUE THREAD

**Issue by defionscode** [ansible/proposals#148]
# Proposal: Audit Modules

*Author*: Jonathan Davila <@defionscode> IRC: defionscode
*Date*: 2018-11-02

- Status: New
- Proposal type: new pattern for modules
- Targeted release: 2.8
- Associated PR: https://github.com/ansible/ansible/pull/47980
- Estimated time to implement: immediate

## Motivation
Currently Ansible is suboptimal for doing "true" audits. Audits, in this context should be understood as the capability to define, analyze, and report (but never change) on _some_ quantity of state:

1. Leverage the data from the audit (regardless of 'passing')
2. Optionally, but not implicitly, cause _tunable_ task-level failures in the event of non-compliance in order to drive logic

### Problems
What problems exist that this proposal will solve?
- Check Mode is not sufficient for true audits because the data is "all over" in that the end user is left to aggregate tons of data across multiple tasks with tons of registered vars which makes any subsequent and dependent logic complicated and not sustainable. This is exacerbated by the fact that not all modules support check mode.
- Forcing usage of a facts module + a subsequent fail/assert task is really a poor UX when the facts of an audit are almost always going to have complex data structures. An end user shouldn't need to be jmespath-competent in order to take advantage of audit data. This is especially true when you consider that audit data usage has a few but well known use cases, when:
  - audits needs to pass all requirements or/then X needs to happen
  - audits needs to pass Y rules or/then X needs to happen
  - audits needs to provide information independent of pass/fail rate

## Solution proposal

The solution is simply to get a 'green light' from the core team on letting this be a new module design pattern. Perhaps even having these types of modules be suffixed by `_audit`, e.g., `scap_audit` or even `scap_facts_audit`.

The pattern I desire, in simplest terms is to allow for facts module that can invoke a _tunable_ task failure when explicitly desired by a user as demonstrated in my PR. The _audit module(s) should never make any changes, they should only ever do read-only types of operations.

## Dependencies (optional)
none

## Testing (optional)
testing would just be a function of unit tests for a given module as demo'd in my PR

## Documentation (optional)
maybe something in dev guidelines + regular ol' module docs

## Anything else?
At this point I refrain from making any suggestions on how things in module_utils could help given the broadness of the 'audit' concept.

**Comment by bcoca** [comment]
I'm unsure why the facts + assert/fails is a bad UX, its a lot more flexible for the user if they want to add validations the module author had not foreseen.

I think this is a good case for making a role that does the gathering and validation, easy enough for a user to expand on it or even reduce it if they are not interested in a lot of the validation.

**Comment by defionscode** [comment]
Take for example STIG or CIS benchmarks. For most OS standards there are well over 200 checks (in some cases over 400 checks). If the data is collected and stored into a complex structure, as is the case with most compliance bodies, then it become unnecessarily difficult to do basic auditing activities as I mention in the proposal. 

In the ansible-lockdown project we attempted to go down the path of having a role that does gathering and validation (and remediation) and it proved to be unsustainable at scale on the gathering front.

For rudimentary/basic things you are correct, a role with some data collection + assert/fail statements is probably a good route.

Having it all-in-one, for lack of better terms, also facilitates much easier reporting. In lockdown we faced the problem of having to scroll through tons of stdout to grok what had actually failed the standard where as with this type of implementation you can gather all that data quickly and present it easily.

To be clear, this is for literal audit use cases where there are clear and objective standards not typically subject to expansion by an end user.

I would gamble that very few organizations use Ansible to do meaningful audits (sans remediation) because it's very difficult to do in way that's useful in an actual audit (even when using Tower).

The failure scenarios these types of modules would have are those that are use cases for _nearly_ everyone. If a more tailored approach is desired then nothing stops a 'power' user from making a role that includes this kind of module + fail/assert statements for more surgical approaches.

A natural evolution to this work that I am contemplating is for Ansible to have a first class capability to ingest OVAL content and use that to drive the underlying python logic of a fact module. That would be the ultimate shiny imo.

**Comment by defionscode** [comment]
Is there a proposal or something similar for the 'assertion modules' you're referencing?

**Comment by bcoca** [comment]
not directly, but https://github.com/ansible/proposals/issues/39 spawned https://github.com/ansible/ansible/pull/44983  and then there is networking's https://github.com/ansible-network/network-engine/blob/devel/action_plugins/validate_role_spec.py

But i think that most of this would be moot if https://github.com/ansible/proposals/issues/136 were implemented

**Comment by defionscode** [comment]
I dont think it'd be moot. The proposal you reference is a good use case for more complex logic or for logic that is better referenced via YAML. 

Otherwise, in the example of the openscap XML report, we'd need to have module that can ingest it (which is done), then a series of json_query set_fact tasks, plus some number of assert tasks with failed_when directives. 

This, imo, is unnecessarily verbose. It's faster and easier to do it in python while exposing only relevant levers to an end user. The role structure does not give an end user anything.

Collapsing into the module's python logic provides convenience

1. it doesn't add a whole new role with what would probably be many lines of YAML and json_query/filter magic
1. provides the benefit of uniformity across users. 
1. A role, a user is expected to potentially change, a module in the upstream, rarely. A module that can get data and optionally fail when explicitly requested would give end users a more consistent experience for a particular type of audit/check.
1. This still allows for a "power" user to _only_ gather facts and do whatever special logic they desire.

**Comment by bcoca** [comment]
I'm not sure you need json_query/set_fact as much as you think, most of those operations can easily just be done in `vars:` for the task.

1) i don't see this as a necessary nor really a negative, i think its more complex for users to deal with actual code
2) This is not approach specific
3) This is also not inherit to the method, just the expectations you are ascribing. I know roles that have changed a lot less than modules in past 5 yrs. It depends more on interface and scope when created than actual implementation method.
4) again, not method dependent, both ways allow for that, but as a single module you cannot reuse the validation part with diff data provider.

**Comment by defionscode** [comment]
> i think its more complex for users to deal with actual code
They wouldnt be expected to for modules like this

> This is not approach specific
not sure what you mean

> I know roles that have changed a lot less than modules in past 5 yrs

Not sure that's applicable here. It's simple to ensure/expect that users have the latest version of module than it is to ensure they have the latest version of a role.

> but as a single module you cannot reuse the validation part with diff data provider.

You shouldnt/wouldnt want to anyways. A data provider in this context is some _thing_ that provides some kind of machine-readable data. Let's use an oscap report as an example again. It doesnt make any sense to use validation logic designed for SCAP audits to be able to validate the data from a non-SCAP derived source. So you're right, you cannot reuse validation, and I that's not desired in this case.

**Comment by bcoca** [comment]
I'm not saying arbitrary sources, but you can have more than one 'scap' data gathering source, there might be other modules that gather the data but more/less of it depending on context, while here you tie both into a specific implementation

**Comment by defionscode** [comment]
in core meeting, we agreed to keep validation out of the fact modules (even for audits)
