### ISSUE TITLE
Integration of the Pacemaker resource management module

### ISSUE THREAD

**Issue by rmeillon** [ansible/proposals#151]
# Proposal: Integration of the Pacemaker resource management module

*Author*: Romain Meillon <@rmeillon>

*Date*: 2019-01-08

- Status: New
- Proposal type: module integration and support
- Targeted release: future release
- Estimated time to implement: unknown

## Motivation
Currently, the pacemaker_cluster module allow to only manage the cluster itself, but there is another module already written (same author from Red Hat) and stable to manage cluster resources and it is very useful.
Sorry, it is my first feature request so I don't know if it is the right way to do it.
Thanks anyway.

## Solution proposal
The module is available here : https://github.com/redhat-openstack/ansible-pacemaker

## Dependencies (optional)
It seems that there is no dependencies.

## Documentation (optional)
The documentation will need to be written.

**Comment by Shaps** [comment]
Hi @rmeillon,

I don't believe new modules require a proposal. A 'Feature request' issue should be more than enough.
