### ISSUE TITLE
Add `--network-segment` support for OpenStack os_subnet module.

### ISSUE THREAD

**Issue by jdiaz9** [ansible/proposals#163]
# Proposal: Add `--network-segment` support for OpenStack os_subnet module.

```
$ openstack subnet create --help
usage: openstack subnet create [-h] [-f {json,shell,table,value,yaml}]
                               [-c COLUMN] [--max-width <integer>]
                               [--fit-width] [--print-empty] [--noindent]
                               [--prefix PREFIX] [--project <project>]
                               [--project-domain <project-domain>]
                               [--subnet-pool <subnet-pool> | --use-prefix-delegation USE_PREFIX_DELEGATION | --use-default-subnet-pool]
                               [--prefix-length <prefix-length>]
                               [--subnet-range <subnet-range>]
                               [--dhcp | --no-dhcp] [--gateway <gateway>]
                               [--ip-version {4,6}]
                               [--ipv6-ra-mode {dhcpv6-stateful,dhcpv6-stateless,slaac}]
                               [--ipv6-address-mode {dhcpv6-stateful,dhcpv6-stateless,slaac}]
                               **[--network-segment <network-segment>]** --network
                               <network> [--description <description>]
                               [--allocation-pool start=<ip-address>,end=<ip-address>]
                               [--dns-nameserver <dns-nameserver>]
                               [--host-route destination=<subnet>,gateway=<ip-address>]
                               [--service-type <service-type>]
                               [--tag <tag> | --no-tag]
                               <name>
```

*Author*: Javier Diaz <@jdiaz9>

*Date*: 2019-05-12

- Status: New
- Proposal type: Module Enhancement (https://docs.ansible.com/ansible/latest/modules/os_subnet_module.html)

## Motivation

The os_subnet module works quite well for most use cases today, however, a relatively new feature in OpenStack known as `routed provider networks` requires that an OpenStack subnet be created with the `--network-segment` flag in order to place the subnet in the proper network segment.

More details:

https://docs.openstack.org/neutron/latest/admin/config-routed-networks.html

### Problems
What problems exist that this proposal will solve?
- As it stands the current module will create automate the subnet creation process, however, the configuration of the network segment must be accomplished as a separate task using `command`. There are also a few other obstacles that one must overcome to make a change like this. For example, one must gather the subnet and segment ID prior to manually adding the subnet to the segment.

-  Alternatively, the entire subnet can be created (network segment included) if the `command` method is used. However, this defeats the purpose of the model. 

## Solution proposal
- Add a new parameter to the module. For example, `segment`. This parameter would be optional.
- A possible example would be:

```
- name: configure subnet with a specific CIDR range to a specific network, project, and segment
  os_subnet:
    state: present
    name: netsub1
    project: admin
    network_name: net1
    cidr: 192.168.0.0/24
    segment: segment1
```

The support of this new parameter will prevent users the need to create separate tasks in order to assign the subnet to a segment.

## Dependencies (optional)

- This flag is dependent on python-openstackclient 3.14.2-0ubuntu1. Otherwise, the flag will yield an unrecognized argument error via the openstack cli.

## Testing (optional)

Deploy an OpenStack cloud, create a network, create a subnet using the os_subnet module.

## Documentation (optional)

Update: https://docs.ansible.com/ansible/latest/modules/os_subnet_module.html

**Comment by agaffney** [comment]
Proposals are for far-reaching changes in Ansible. This should be a simple feature request in the `ansible/ansible` repo.

**Comment by jdiaz9** [comment]
Thanks, will close and move to `ansible/ansible`.
