### ISSUE TITLE
Create OpenStack module to support create/delete/update network segments

### ISSUE THREAD

**Issue by jdiaz9** [ansible/proposals#164]
# Proposal: Create OpenStack module to support create/delete/update network segments

*Author*: Javier Diaz <@jdiaz9>

*Date*: 2018-MM-DD

- Status: New
- Proposal type: New OpenStack module

## Motivation

A relatively new OpenStack feature known as `routed provider networks` requires network segments be created and tied to subnets within the same network.

Routed provider networks is quickly becoming a necessary implementation in large enterprise grade deployments where different racks/pods of compute nodes need to be added to the cloud.

A reference to routed provider networks: https://docs.openstack.org/neutron/latest/admin/config-routed-networks.html

### Problems
What problems exist that this proposal will solve?
- As it stands, there is no Ansible OpenStack module to assist with this. The way around this is to pass environment variables and use `command`. For example:

```
- name: create network segment for {{ network.name }}
  command: "openstack network segment create --physical-network {{ network.name }} --network-type flat --network {{ network.name }} {{ network.name }}-segment-1"
```

## Solution proposal
- Create a new module similar to the `os_network` and `os_subnet` modules that accomplishes the same functionality provided in the `openstack network segment {create, delete, list, set, show}` cli.

## Dependencies (optional)
- Requires python-openstackcli 3.14.2.

## Testing (optional)
Deploy an OpenStack cloud, create network, create segments.

**Comment by agaffney** [comment]
Proposals are for far-reaching changes in Ansible. This should be a simple feature request in the `ansible/ansible` repo.

**Comment by jdiaz9** [comment]
Thanks, will move to `ansible/ansible`. Will close.
