### ISSUE TITLE
add_host module

### ISSUE THREAD

**Issue by mgup73** [ansible/proposals#166]
# Proposal: <proposal name>

*Author*: Your Name <@yourGHid> IRC: handle (if different)

*Date*: 2018-MM-DD

- Status: New
- Proposal type: (core design, process, ?)
- Targeted release: <future release #, ex. 2.2>
- Associated PR: <link to GH PR in ansible/proposals if PR was submitted>
- Estimated time to implement: <X days, weeks, etc.>

## Motivation
Describe the reasons for this proposal.

### Problems
What problems exist that this proposal will solve?
- Problem #1
- Problem #2
- Or just describe the problem if there is just one.

## Solution proposal
- Describe your suggested solution here.
- Insert code in snippets if you would like as shown.
```yaml
    - include: main.yml
      vars:
         var1: val1
```
- Be sure to explain how this solves problems.

## Dependencies (optional)
Explain any dependencies. This section is optional but could be helpful.
- Dependency #1
- Dependency #2

## Testing (optional)
Does / should this require testing, and if so, how? Describe here. This section is optional but could be helpful.

## Documentation (optional)
Does / should this require documentation? If so, describe here. This section is optional but could be helpful.

## Anything else?
If you'd like to add anything else beyond the above required and optional sections, you are welcome to do so.

**Comment by mgup73** [comment]
I don't know its a issue or my understanding is wrong.. I am using add_host module and in this module I have to change groupname every time I am running the script. And more than two hosts can be added but unable to ping to all just the latest one.

**Comment by Akasurde** [comment]
@mgup73 Please use https://github.com/ansible/ansible/issues/new?template=bug_report.md for reporting this issue. This repository is meant for Ansible Proposals. Thanks.

**Comment by mgup73** [comment]
sorry.
