### ISSUE TITLE
improvement proposals for Ansible Tower job details view

### ISSUE THREAD

**Issue by AlexanderStohr** [ansible/proposals#172]
improvement proposals for Ansible Tower job details view:
1) change the text in the search box from "[...] still running" to "[...] running"
2) change the text top right of "extra variables" box from "EXPAND" to the same maximize icon as on the right frame. (this unifies the controls of the web UI)
3) add a "raw data download" button for the logged texts

**Comment by matburt** [comment]
You should open this as a feature request in `ansible/awx` instead.
