### ISSUE TITLE
Being able to do a "pause" during a running job in tower

### ISSUE THREAD

**Issue by dapiced** [ansible/proposals#177]
# Proposal: Being able to do a "pause" during a running jobs in tower

*Author*: Your Name @dapiced

*Date*: 2020-01-27

- Status: New

## Motivation/Problems
Sometime we need to use tower-cli to cleanup inventory, but if jobs is runnings, the inventory is block for tower-cli

## Solution proposal
Being able to do a "pause" during a running job in tower, like a PAUSE BUTTON

**Comment by sivel** [comment]
Thank you for your interest in Ansible. This proposals project is intended for proposals for the ansible/ansible project, and not for Tower or AWX.  Please open this as a feature request at http://github.com/ansible/awx/issues/
