### ISSUE TITLE
Ansible Inventory Host Enabled/Disabled Flag

### ISSUE THREAD

**Issue by nmajin** [ansible/proposals#187]
# Proposal: 

*Author*: Mark @nmajin

*Date*: 2021-01-07

- Status: New
- Proposal type: Core
- Targeted release: 2.11
- Associated PR: N/A
- Estimated time to implement: N/A

## Motivation
Red Hat provides the option of importing a YAML Ansible Engine inventory into Tower but the Enabled/Disabled host flags cannot be used. We have some cases where we would like these to toggled or synced from the YAML inventory to Tower even.

### Problems
What problems exist that this proposal will solve?
Keeping an Ansible Engine inventory TRULY in-synch with an Ansible Tower inventory

## Solution proposal
Provide a flag in the YAML version of the Ansible Engine inventory that mirrors the Enabled/Disabled host flag in an Ansible Tower Inventory

- Be sure to explain how this solves problems.

## Dependencies (optional)
Explain any dependencies. This section is optional but could be helpful.
Make sure the change introduced an Ansible Engine inventory works to change the state in an Ansible Tower inventory

## Testing (optional)
N/A

## Documentation (optional)
Yes, this should be a core feature documented

## Anything else?
No

**Comment by bcoca** [comment]
This would have to be added to awx/tower import, this is not the correct forum for that. For AWX features you should post issues at https://github.com/ansible/awx/issues.

Also, good news, the feature already exists and is in version 3.8.  https://docs.ansible.com/ansible-tower/latest/html/userguide/inventories.html#add-source see step 7

**Comment by nmajin** [comment]
> This would have to be added to awx/tower import, this is not the correct forum for that. For AWX features you should post issues at https://github.com/ansible/awx/issues.
> 
> Also, good news, the feature already exists and is in version 3.8. https://docs.ansible.com/ansible-tower/latest/html/userguide/inventories.html#add-source see step 7

Thanks for the reply, and good news!
