### ISSUE TITLE
Ansible Feature Request

### ISSUE THREAD

**Issue by AbbyIMT** [ansible/proposals#195]
# Proposal: <proposal name>

*Author*: Abdulla <@AbbyIMT> IRC: handle (if different)

*Date*: 2018-06-28

- Status: New
- Proposal type: UI Feature request
- Targeted release: <future release #, ex. 2.2>
- Associated PR: <link to GH PR in ansible/proposals if PR was submitted>
- Estimated time to implement: <X days, weeks, etc.>

## Motivation
To make it more easier

## Solution proposal
I am learning Ansible and got this feature request, which came from an discussion i had long time ago with a programmer. He had desigined a application for developers where developers choose what they want in the application with click & drag feature and customize.

If Ansible Tower should have a YAML editor. This editor must show all modules of a specific device that a user selects. For example i select Cisco or F5 device and it should show all modules and what they do and it should be click and drag and make your YAML. The code should be built automatically once the module is drag & then the editor must show red marked area where user needs to put the variables etc. Once ready it can be saved locally or to a SCM if Tower is connected to it.

If this is possible, Ansible will become super easy.

**Comment by bcoca** [comment]
For the OSS version (AWX) https://github.com/ansible/awx

This issue tracker is for the open source Ansible CLI tools project.

**Comment by thaumos** [comment]
@AbbyIMT,

Thank you so much for your proposal on this feature.  

We are definitely looking into improving the experience for creating content in Ansible Automation Platform. 

While the feature you have requested may or may not appear in the way you had suggested, please stay tuned to updates on everything related to features we provide for AAP and creators in the future :).  I am super excited for everyone to try these new features out.
