### ISSUE TITLE
Add support for fetching SSH private keys from AWS SSM Parameter Store/AWS Secrets Manager 

### ISSUE THREAD

**Issue by akr257** [ansible/proposals#196]
# Proposal: Add support for fetching SSH private keys from AWS SSM Parameter Store/AWS Secrets Manager 

*Author*: akr257

*Date*: 2021-07-14

- Status: New
- Proposal type: core design
- Targeted release: N/A
- Associated PR: N/A
- Estimated time to implement: N/A

## Motivation
We currently store our SSH private keys for our EC2 instances in SSM Parameter Store and AWS Secrets Manager. 
We would like the ability to specify the SSM Parameter Path in the inventory file so the Ansible controller can fetch it directly. 
The current workaround involves:
[1] Fetching the SSM parameters outside of the Ansible playbook 
[2] Update the permissions of the private key file

## Solution proposal
It would be great if we could define another variable e.g. `ansible_ssh_private_key_aws_ssm_path=/my/private/key`

**Comment by mkrizek** [comment]
This should be a feature request in https://github.com/ansible-collections/amazon.aws.
