### ISSUE TITLE
Ansible control node for IBM Z in a Linux/390 Docker container for z/OS Container Extensions

### ISSUE THREAD

**Issue by ndegreef** [ansible/proposals#198]
# Proposal: Ansible control node for s390 in z/OS docker container

*Author*: @ndegreef

*Date*: 2021-07-23

- Status: New
- Proposal type: Ansible docker for IBM Z
- Targeted release: 2.9
- Associated PR: N/Z
- Estimated time to implement: unknown

## Motivation
On IBM Z we see more and more use of Ansible. Therefore we would like to be able to run an Ansible control node on IBM Z on z/OS itself in a Docker container under Z/OS Container Extension.

### Problems
What problems exist that this proposal will solve?
- Ansible in a zCX container make z/OS management through Ansible much easier to manage and secure.
- Running Ansible in a z/OS context prevents the need for additional management platforms, simplifying the whole setup.

## Solution proposal
- Provide Ansible as a Linux s390 Docker container.

## Dependencies (optional)
The usual prereqs for Ansible like Python and ssh but these are all available for Linux s390 already.

**Comment by agaffney** [comment]
Ansible doesn't provide *any* official Docker images for any architecture, and there's nothing stopping you from building your own custom image containing Ansible.

**Comment by bcoca** [comment]
closing as per above, the Ansible project does not and is not planning on maintaining 'official' container images.
