### ISSUE TITLE
Schedule tasks

### ISSUE THREAD

**Issue by jeroentje91** [ansible/proposals#199]
# Proposal: <proposal name>

*Author*: Your Name <@yourGitHubID> IRC: handle (if different)

*Date*: 2018-MM-DD

- Status: New
- Proposal type: (core design, process, ?)
- Targeted release: <future release #, ex. 2.2>
- Associated PR: <link to GH PR in ansible/proposals if PR was submitted>
- Estimated time to implement: <X days, weeks, etc.>

## Motivation
At this point in AWX we can schedule templates. 
If it would be possible to also scedule jobs based on that template.  

### Problems
What problems exist that this proposal will solve?
When you want to block a specific account on a specific time then this is not possible at the moment using AWX 

## Solution proposal
The option to scedule jobs instead of only templates. 
```
This way ansible/AWX is more flexible

## Dependencies (optional)
Explain any dependencies. This section is optional but could be helpful.
- Dependency #1
- Dependency #2

## Testing (optional)
testing the sceduling of tasks instead of templates

## Documentation (optional)
Yes, how to scedule a task

## Anything else?
If you'd like to add anything else beyond the above required and optional sections, you are welcome to do so.

**Comment by sivel** [comment]
The AWX project does not use this proposals project to track requests. This is primarily only for ansible-core.

Please feel free to open a feature request at https://github.com/ansible/awx/issues/new?assignees=&labels=&template=feature_request.md
