### ISSUE TITLE
Ansible AWX Status is Disabled

### ISSUE THREAD

**Issue by ekharrat** [ansible/proposals#208]
Hello

i installed ansible awx with docker containers, whenever i create an inventory its status is showing disabled as shown in the attached screenshot , your assistance is appreciated
![disabled_inv](https://user-images.githubusercontent.com/120107931/206455781-cca8a125-45eb-4347-8a00-c9f89aa7eaf9.PNG)
 .

**Comment by mkrizek** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible-awx on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/awx-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
