### ISSUE TITLE
Tooling for creating templates from skeletons for anything related to ansible.

### ISSUE THREAD

**Issue by minsis** [ansible/proposals#213]
# Proposal: Skeleton Templating Tooling

*Author*: Dennis Whitney <@minsis> IRC: people still use IRC?

*Date*: 2024-11-26

- Status: New
- Proposal type: design
- Targeted release: ?
- Associated PR: N/A
- Estimated time to implement: 1-2 weeks

## Motivation
`ansible-galaxy` has skeleton templating builtin for creating collections or roles based off some templating. Other areas are missing this feature for creating playbooks and maybe even configuration files.

In our company we require certain standards for playbook names, functionality, configuration, etc. Today I have a playbook that builds playbooks based off a set of variables passed into `--extra-vars`. It would be nice to see this extended into other tooling, or maybe the better use case is to have a dedicated tool to do this. Something like `ansible-skeleton` or `ansible-template`.

### Problems
What problems exist that this proposal will solve?
- As stated above we require a specific structure and naming of playbooks so we need to templatize it ourselves with an Ansible playbook

## Solution proposal
My suggestion is to build tooling to allows for creating templates across the board. Something like ansilbe-sekleton or ansible-template would allow for base templating of anything related to Ansible. The templating structure built into ansible-galaxy could also be moved into this singular tool.

Doing the would allow extending templating for anything that could be related to Ansible like configuration files, Dockerfiles, etc.

## Dependencies (optional)
N/A

## Testing (optional)
Testing would be isolated to the tool and should be simple to test.

## Documentation (optional)
Everything should be documented, this shouldn't be a question! :)

## Anything else?
No.

**Comment by s-hertel** [comment]
Fwiw, you can bring your own skeleton which could contain anything. 2.17+ supports `--extra-vars` for init, so custom skeletons are no longer limited by the few, hardcoded variables ansible-galaxy provides to template .j2 files in the skeleton.

`ansible-galaxy collection init --collection-skeleton /path/to/your/skeleton --extra-vars @/path/to/vars.yml`.

Also if you haven't seen, you might be interested in: https://github.com/ansible/ansible-creator/tree/create.

**Comment by minsis** [comment]
Thanks, I didn't realize there was a tool already for this.

I already knew about ansible-galaxy, but it doesn't include playbooks.

It also looks like ansible-creator is lacking in some features as well. I'll start those discussions over there.
