### ISSUE TITLE
auth_plugins (name is not final, bikeshed away)

### ISSUE THREAD

**Issue by bcoca** [ansible/proposals#24]
# Proposal: auth_plugins

_Author_: Brian Coca @bcoca

_Date_: 2016/07/23
- Status: New
- Proposal type: core design
- Estimated time to implement: weeks
## Motivation

Plugins that use an API don't have a good way to deal with secondary authentication, connection plugins cannot provide these in a transparent fashion nor would they be 'plugin specific'. 
### Problems
- cloud modules (aws/gce/azure/etc) and network appliance ones (ios/juniper/cumulus/etc) all have this issue and either rely on an external library/environment setting up the auth and reusing that data or the users themselves have to repeat the auth info in every task when invoking these plugins.
- lookups and callbacks that also need authentication (mail, jabber, consul, etc) also have to rely on clunky env vars or other setups to access these services.
## Solution proposal
- A new plugin type auth_plugin, which modules, lookups and callbacks can use by 'requiring them'.
- Once invoked an auth_plugin should be able to take existing env vars/libraries as we currently use, but also access inventory vars specific to the plugin (ansible_auth_aws_secret?) to allow transparent inventory configuration for hosts/groups as we do for connections.
- plugins will now only need 1 interface and push all the complex code of getting the auth from different sources and fallbacks and just deal with using the object/token needed for communication with the API. 
- Users will only need to provide the data 1 time or in one place, existing plugins can keep the current auth options for backwards compatibility.
- The auth plugin is executed from the same target as the invoking plugin, so ansiballz needs to be able to ship them to the targets with modules. The target MUST have any required libraries for the auth plugin to execute (which should not change existing workflows as this is already required by the modules). If the auth data is provided at the controller side, it must be shipped to the auth plugin.
- Depending on API, return data from auth plugin can/should be appended to module return data and persisted/fed back when needed. This data is 'host dependant', as most API/services will not work well with auth tokens across hosts. (special treatment of ansible_auth in return?). This data should also be treated as confidential and avoid any disclosure.
## Documentation

Each auth plugin should document all possible data sources (environment, existing libs, inventory vars) and the returned object/token for use by the plugin.

**Comment by jhawkesworth** [comment]
I like this idea a lot.  Could play well with windows where sometimes you have to log in as local administrator (when first setting up a machine) but may later need to log in as a domain user.
A convention for auth plugin inventory var names (starting with 'ansible_auth_<plugin_name>_' perhaps might be a nice thing so you can know by looking at inventory / group_vars what auth plugins are configured for a host/group.

**Comment by bcoca** [comment]
@jhawkesworth the auth plugins I propose would not affect connections nor 'become' functionality, they would just setup auth and provide it to modules that execute using that auth (aws, ios, etc).

**Comment by tima** [comment]
@bcoca would this solve some of the more complex synchronize issues we've seen as issues?

**Comment by bcoca** [comment]
@tima I had not thought about application for syncronize, but it probably could for cases in which controller is not either src or dest.

**Comment by ram-ibm** [comment]
@bcoca any update if we can expect this in the near future please?

**Comment by bcoca** [comment]
@ram-ibm no .. not until we figure out how to fix issues with action plugins

**Comment by cognifloyd** [comment]
I do this in my custom lookups and actions: If the playbook user doesn't provide a set of vars used for authentication on the task itself, I use self._templar to fill in those vars. In many cases, that means that the inventory_host has to set the host name of the service host (the host that I'm authenticating against), and then I use a template like `self._templar.template("hostvars['{}']['my_service_username']".format(service_host))`. But, that means I have to reimplement this for lookups, actions, etc. Auth plugins sounds fantastic. I look forward to using them.

**Comment by jamescassell** [comment]
Once these are a thing, it would be good if the auth plugin can include a delegate_to host automatically, such as for cloud modules that generally delegate_to localhost (or the playbook targets localhost.)

**Comment by bcoca** [comment]
abandoning this idea, thinking a data structure is a better implementation, `module_defaults` keyword is already an example avenue to this goal.
