### ISSUE TITLE
Top-level module directory reorg

### ISSUE THREAD

**Issue by nitzmahone** [ansible/proposals#46]
# Proposal: Top-level module directory reorg

*Author*: Matt Davis <@nitzmahone>

*Date*: 2016/12/19

- Status: New
- Proposal type: process
- Targeted Release: 2.3
- Estimated time to implement: 2 days

## Motivation
It's very difficult to locate the code for a module today. The current file layout based on categories is somewhat arbitrary for a number of modules. Now that we have module metadata, the categories should be reflected there instead of via the physical file path in the repo. The modules should be filed simply by the first letter of their names, making it trivial to locate the code without a search, and reducing the need to move files around as metadata changes.

### Problems
- Locating a module's code can be difficult without search (or a priori knowledge of what category it lives in).
- Moving module code around as metadata changes is dumb.

## Solution proposal
Capture current module category information in module metadata. Move all modules to a simple flat directory structure by the module name's first letter (eg, `win_updates` would live under `modules/w`). Update doc generation to fetch category info from metadata instead of file path.

The 26 dirs under `modules/` aren't strictly necessary either, but the GitHub web UI truncates directory listings after 1000 entries (and in some cases won't show them at all if too large), so having a way to keep the file counts low-ish is important. Since the current module location code already traverses a couple layers of subtrees, we could easily add the second letter of the module names as a subtree underneath later, should a given letter's module file count approach 1000.

## Dependencies (optional)
- HTML docgen update
- Translate path category info to module metadata

**Comment by bcoca** [comment]
If going this route, I would go one step further and make the metadata a 'tag cloud' and remove the current module 'classification', many of them can be looked at from different categories.

**Comment by mattclay** [comment]
Another "soft" dependency is module unit test organization. The directory structure for placement of module unit tests under `test/units/modules` should reflect the organization of the modules.

**Comment by nitzmahone** [comment]
@bcoca: totally agree- IIRC it's already like that internally in the doc generator anyway, so this would just make that explicit (list of categories in metadata, not just one).

**Comment by mattclay** [comment]
Also, various test related files will need to be updated to reflect the new paths, including:

- https://github.com/ansible/ansible/blob/devel/test/compile/python2.4-skip.txt
- https://github.com/ansible/ansible/blob/devel/test/sanity/code-smell/use-compat-six.sh
- https://github.com/ansible/ansible/blob/devel/test/sanity/validate-modules/skip.txt

The first one is the most troublesome, as we'll no longer be able to exclude entire groups of modules from python 2.4 compilation, but instead will need to list each module individually.

**Comment by gundalow** [comment]
Lots (599) modules have a `_` in them to define a grouping.

It feels like they should be directories

5+ are
```
5	digital
5	ecs
5	eos
5	s3
5	udm
5	vertica
5	webfaction
5	zabbix
6	docker
6	gce
6	junos
6	postgresql
7	cl
7	quantum
8	rabbitmq
9	ipa
10	clc
11	pn
16	netapp
17	azure
21	vmware
23	bigip
25	rax
35	cs
37	ovirt
41	os
41	win
44	ec2
65	nxos
```

If we just split on first character we will end up with something like
```
      2 y
      3 x
      7 k
      7 q
      7 t
      9 z
     10 f
     10 h
     11 j
     11 u
     16 m
     19 l
     27 g
     29 b
     34 d
     36 i
     37 v
     45 a
     47 s
     48 p
     48 w
     54 r
     66 e
     71 c
     92 n
     97 o
```

Same data alphabetical
```
     45 a
     29 b
     71 c
     34 d
     66 e
     10 f
     27 g
     10 h
     36 i
     11 j
      7 k
     19 l
     16 m
     92 n
     97 o
     48 p
      7 q
     54 r
     47 s
      7 t
     11 u
     37 v
     48 w
      3 x
      2 y
      9 z
```

**Comment by gundalow** [comment]
Discussed in Core Meeting 2016-12-20

Agreed: 
* move docsbuild to use metadata
* revisit dir structure in future release (don't want to change too much at once)

**Comment by abadger** [comment]
Pure alpha won't always be easier to locate than category dirs... For instance, Is that ec2 module an aws-foo or ec2-foo?  It can also make group changes harder... All amazon modules should now use ansible.module_utils.aws.new_initialization_routine().  Would need a tool that utilizes metadata to find the list of modules instead of going through a single directory.

**Comment by gundalow** [comment]
Once this has been decided we may wish to move `MAINTAINERS.txt` into the main `ansible/ansible` repo.

**Comment by alikins** [comment]
For module dir layout, I would like to see the modules split by runtime/type. ie, python (~1139) vs ps1 (~56).
And then perhaps further split by python/powershell version required.

A very rough approximation of the min python versions required (based on pyqver so just based on use of syntax and stdlib apis without considering python package deps):

```
[fedora-25:ansible (facts_notes %)]$ find lib/ansible/modules -type f -name '*.py' | xargs pyqver2| sort -h | cut -f1| uniq -c | sort -rn
    480 2.2
    219 2.6
    172 2.0
    123 2.5
    114 2.4
     20 2.3
      3 3.1
```

(Ignoring that default module_utils requires python 2.6 for now...)
So maybe 'python-2.4/' (114+20+480+172=786), 'python-2.5/' (123), 'python-2.6/' (219), 'python-2.7/' (~14), 'python-3.1' (3)

Why split by required runtime version? So we could eventually choose the appropriate module implementation (and/or module_utils implementation) based on the runtime available on the target client.

Even if 99% of current modules in up 'python-2.6/*', it would still make it easier for plugin loader and module_common to know its dealing with python modules vs powershell modules. See
https://github.com/ansible/ansible/compare/devel...alikins:module_sdk for an rough prototype of how that could be used.

Also see https://github.com/ansible/ansible/compare/devel...alikins:module_namespace_metadata_filter for an example of a flexible way to resolve module names to a more specific module (ie, 'copy' -> 'copy.py' or 'win_copy.ps1' or '2_3_copy.py' etc)

**Comment by bcoca** [comment]
collections 'solved' this issue by keeping the list of modules in one place down to minimum (sub dirs also removed from core). closing this issue as it is not relevant anymore.
