### ISSUE TITLE
Continuation of original proposals_process_proposal discussion

### ISSUE THREAD

**Issue by robynbergeron** [ansible/proposals#5]
Creating an issue here, linking to the proposal after it was moved from ansible/docs/proposals. 
Current version is located [here](https://github.com/ansible/proposals/blob/master/proposals_process_proposal.md).

[Historical version, for posterity, can be seen here.](https://github.com/ansible/ansible/commit/250b6c0f3552f7f4bac4a9480c45f8d05f7c6e64)

**Comment by robynbergeron** [comment]
So, after some discussion with @gregdek -- want to make a few suggestions on this. 

Our goals in having a proposal process were more or less as follows:

1. Make sure contributors to Ansible can easily suggest more complex / intricate changes to the code base before implementing them, so they can (a) gather feedback, (b) avoid writing a lot of code that may not be merged.
2. Fix the problem of people creating proposals via mailing list, as this is the current default suggested method for discussion on topics like this, since there was is way there to track them or ensure discussion had concluded. The goal is not to give *permission*, really, but more to ensure that people feel like some sort of consensus had been reached, and they can feel more confident in moving ahead. 
3. Make sure that things that are having difficulty in gathering consensus can be easily identified and brought to a meeting for discussion / conclusion, so people can move ahead. 

Current problems I see with the PR process as originally suggested:
1. Every PR needs to be merged. This could be automated, but so could a lot of other things, and that time is probably better spent on automating other things. :smiley: 
2. Possible confusion around "does my PR being merged mean that this is approved."
3. Since the PRs are merged immediately, adding labels that we could use to track them is harder, which means manually viewing the status line in each proposal. 
4. What to do with the proposal documents after they've been through the process? Do we move them to another folder? Leave them in ansible/proposals to rot? 

So. New suggestion: Rather than creating a PR for each proposal, use the "template" function now graciously provided by GitHub and have folks create an issue instead. This provides a few benefits:
1. We can easily use labels to track what is new, "approved" / looks good to go ahead, label specific things for meetings. 
2. Eliminate the need to constantly have PRs being merged. 
3. Avoid accumulation of proposals. (Though, we can have the option for folks to still create a PR.) The proposer can either (a) edit the original issue, or (b) copy/paste the original issue into a comment and edit any updates. 
4. Provide an easy way for people to search past / existing proposals (some things may have already been suggested and approved or declined in the past). 

One area where it may or may not be a benefit:
One of the advantages seen in having a PR (or merged proposal) was that people could update it and be able to view / comment on the history or additional PRs to that proposal. We can do the same thing with issues but I'm not the history winds up being as clear if they are editing their original issue text (since they may edit it as it moves along, and then new readers may lose context.)

But overall: I feel like it is less overhead, and easily trackable, and would still meet our goals. 

Discuss? :)

**Comment by robynbergeron** [comment]
Also: In the spirit of "trying this out" -- I have created an ISSUE_TEMPLATE.md for this repo to demonstrate how it might look. So you can click on "new issue" and see it, right now! 

Or click [this](https://github.com/ansible/proposals/issues/new) which will take you directly there :)

**Comment by gregdek** [comment]
I like this a lot.

On Wed, Mar 30, 2016 at 2:08 PM, Robyn Bergeron <notifications@github.com>
wrote:

> Also: In the spirit of "trying this out" -- I have created an
> ISSUE_TEMPLATE.md for this repo to demonstrate how it might look. So you
> can click on "new issue" and see it, right now!
>
> Or click this <https://github.com/ansible/proposals/issues/new> which
> will take you directly there :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ansible/proposals/issues/5#issuecomment-203559475>
>



-- 
Greg DeKoenigsberg
Ansible Community Guy

**Comment by gregdek** [comment]
This is agreed, so we can close. :)
