### ISSUE TITLE
Create supported_by: core_network metadata tag

### ISSUE THREAD

**Issue by thaumos** [ansible/proposals#53]
# Proposal: Add 4th metadata tag for supported_by called core_network

*Author*: Dylan Silva <@thaumos>

*Date*: 2016/02/14

- Status: New
- Proposal type: Core Design
- Targeted Release: 2.3 / 2.4
- Associated PR: TBD
- Estimated time to implement: 1 day

## Motivation
To further classify supported network modules on documentation and for support related contracts. 

### Problems
What problems exist that this proposal will solve?
The ability to quickly decipher what modules are supported under certain contracts and by whom in our teams.

## Solution proposal
Change metadata supported_by tags from core to core_network on applicable modules.

Note: We won't bump the metadata version number for this change as there hasn't been any release of Ansible with the metadata in it yet.

### What needs to be changed

* Documentation of the Ansible Metadata will need to be updated.  Documentation is currently being created here: https://github.com/ansible/ansible/pull/21250

**Comment by bcoca** [comment]
composite values are not the best way to handle metadata, each value should have it's own field

support: core <- expect 'ansible inc' backed support
team: networking/core/maintainers/vendor

**Comment by thaumos** [comment]
we need a value to differentiate these subset of modules for support; which is why I suggested "network". am open to suggestions on what to call it though.

**Comment by thaumos** [comment]
closing as it doesn't really apply.
