### ISSUE TITLE
Publish / Subscribe for Handlers

### ISSUE THREAD

**Issue by resmo** [ansible/proposals#8]
# Proposal: Publish / Subscribe for Handlers

*Author*: René Moser <@resmo>

*Date*: 2016/03/07

- Status: New
- Proposal type: core design
- Targeted Release: N/A
- Associated PR: N/A
- Estimated time to implement:  N/A

## Motivation

In some use cases a publish/subscribe kind of event to run a handler would be more convenient. A typical example is: restart services using SSL after replacing SSL cert files. Ansible does not provide a built-in way to handle it yet.

### Problem

If you copy SSL cert fles to your systems, you usually have to reload/restart services used the previous SSL cert file to use the new certificate.

However, If you have a ssl role or a generic ssl playbook, you usually don't want to add specific handlers to it. Instead it would be much more convenient to use a publish/subscribe kind of paradigm in the roles where the services are configured in.

The way we were able to implemented it currently without publish/subscribe:

Use notify to set a fact where later (in different plays) act on a fact using notify again.

~~~yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: copy an ssl cert
    shell: echo cert has been changed
    notify: publish ssl cert change
  handlers:
  - name: publish ssl cert change
    set_fact:
      ssl_cert_changed: true

- hosts: localhost
  gather_facts: no
  tasks:
  - name: subscribe for ssl cert change
    shell: echo cert changed
    notify: service restart one
    when: ssl_cert_changed is defined and ssl_cert_changed
  handlers:
  - name: service restart one
    shell: echo service one restarted

- hosts: localhost
  gather_facts: no
  tasks:
  - name: subscribe for ssl cert change
    shell: echo cert changed
    when: ssl_cert_changed is defined and ssl_cert_changed
    notify: service restart two
  handlers:
  - name: service restart two
    shell: echo service two restarted
~~~

However, this looks like a workaround of a feature that ansible should provide in a much cleaner way.

### Approach 1:

Provide new `subscribe` keyword on handlers:

~~~yaml
- hosts: localhost
  gather_facts: no
  tasks:
  - name: copy an ssl cert
    shell: echo cert has been changed

- hosts: localhost
  gather_facts: no
  handlers:
  - name: service restart one
    shell: echo service one restarted
    subscribe: copy an ssl cert

- hosts: localhost
  gather_facts: no
  handlers:
  - name: service restart two
    shell: echo service two restarted
    subscribe: copy an ssl cert
~~~

### Approach 2:

Provide new `subscribe` on handlers and `publish` keywords in tasks:

~~~yaml
- hosts: localhost
  gather_facts: no
  tasks:
  - name: copy an ssl cert
    shell: echo cert has been changed
    publish: yes

- hosts: localhost
  gather_facts: no
  handlers:
  - name: service restart one
    shell: echo service one restarted
    subscribe: copy an ssl cert

- hosts: localhost
  gather_facts: no
  handlers:
  - name: service restart two
    shell: echo service two restarted
    subscribe: copy an ssl cert
~~~

### Approach 3:

Provide new `subscribe` module:

A subscribe module could consume the results of a task by name, optionally the value to react on could be specified (default: `changed`)

~~~yaml
- hosts: localhost
  gather_facts: no
  tasks:
  - name: copy an ssl cert
    shell: echo cert has been changed

- hosts: localhost
  gather_facts: no
  tasks:
  - subscribe:
      name: copy an ssl cert
    notify: service restart one
  handlers:
  - name: service restart one
    shell: echo service one restarted

- hosts: localhost
  gather_facts: no
  tasks:
  - subscribe:
      name: copy an ssl cert
      react_on: changed
    notify: service restart two
  handlers:
  - name: service restart two
    shell: echo service two restarted
~~~

### Approach 4:

Provide new `subscribe` module (same as Approach 3) and `publish` keyword:

~~~yaml
- hosts: localhost
  gather_facts: no
  tasks:
  - name: copy an ssl cert
    shell: echo cert has been changed
    publish: yes

- hosts: localhost
  gather_facts: no
  tasks:
  - subscribe:
      name: copy an ssl cert
    notify: service restart one
  handlers:
  - name: service restart one
    shell: echo service one restarted

- hosts: localhost
  gather_facts: no
  tasks:
  - subscribe:
      name: copy an ssl cert
    notify: service restart two
  handlers:
  - name: service restart two
    shell: echo service two restarted
~~~

### Clarifications about role dependencies and publish

When using service roles having the subscription handlers and the publish task (e.g. cert change) is defined in a depended role (e.g. SSL role) only the first service role will trigger the publish running the "cert change" task as dependency.

In any other service role in the playbook having "SSL role" as dependency, the task won't be `changed` anymore.

Therefore a once published "message" in a play should not be overwritten or so called "unpublished" running the same task again.

## Feedback

Feedback is requested to improve any of the above approaches, or provide further approaches to solve this problem.

**Comment by bcoca** [comment]
So I'm not clear on the problem, as currently handlers 'subscribe' by their `name`, and we `publish` to that name also through `notify`, so this does not seem to change anything except adding new keywords. 

The thing that does seem like a significant change is making handlers global and not 'play scope', which does not require subscribe/publish but a change to assign them to the playbook or run.

**Comment by resmo** [comment]
The difference is the task which *publishes* a change has no knowledge about handlers or how many handlers will be executed later in other plays. 

We *must not explicitly* name the handlers nor know any potential handler which needs to be run at the task.

**Comment by bcoca** [comment]
in 2.x that is not needed either, just need the names to match as handler existence is not checked for, a simple switch to make it a 'non error' would suffice (I would recommend a toggle config).

**Comment by resmo** [comment]
key sentence is "need the (handler) names to match" which I tried to reverse by this proposal.

**Comment by bcoca** [comment]
match notify to handler or handler to notify, same thing

**Comment by abadger** [comment]
I like Approach 1 &  2 much better than 3 & 4.

**Comment by bcoca** [comment]
after meeting, only real agreement is that events/handlers should stay in play scope.

@resmo, please reformat proposal with exactly what features are expected and present use cases.

**Comment by jimi-c** [comment]
The method I would like to see in the proposal:

1. Add subscribe field to Handler
2. When we load handlers don't just build a mapping of their names but also build one of their subscriptions
3. When we send a notify, if we don't find the notification string in the name mapping, look in the subscriptions mapping

**Comment by abadger** [comment]
This was accepted at the meeting with @jimi-c to work on implementation.

**Comment by resmo** [comment]
replaced with a more detailed proposal #11
