### ISSUE TITLE
Ansible sub-packages for easy dependencies install

### ISSUE THREAD

**Issue by kustodian** [ansible/proposals#87]
# Proposal: Ansible sub-packages for easy dependencies install

*Author*: Strahinja Kustudic @kustodian

*Date*: 2017/11/03

- Status: New
- Proposal type: packaging
- Targeted Release: 2.5

## Motivation
This is a follow up to https://github.com/ansible/ansible/pull/31719#issuecomment-337948271. Instead of adding additional dependencies into Ansible base packages, we should create additional Ansible packages which will make it easy to install all Ansible dependencies for filters, lookups, modules, etc.

### Problems
- When a user installs the `ansible` package, that doesn't mean all the filters, lookups, plugins, etc will work. To resolve this issue a user needs to install additional python packages, usually using an Ansible playbook or some other way.
- We should make it easier to install Ansible with all it's dependencies on control machines
- Give the user flexibility to install only what the user needs

## Solution proposal
- The idea is to provide additional `ansible-*` packages which will install dependencies for different types of Ansible modules, filters, lookups, etc.
 - These packages could just have deps to needed python packages, but they could also contain python modules (in cases when the distribution doesn't provide the needed python packages), but this can be further discussed. Make sure to check [comments](https://github.com/ansible/ansible/pull/31719#issuecomment-337972608) by @alikins in the old PR. 
 - We still have to decide how exactly are these new packages going to be called and how will they be grouped, e.g. ansible-community-filters, ansible-aws-plugins, etc.

## Documentation (optional)
Installation part of the documentation would need to be updated with the list of these packages.

**Comment by bcoca** [comment]
Closing this as 'collections' have opened this up for distro packagers to handle it directly. 

We already provide an `ansible-core` package with minimal dependencies and collections provide most other plugins and modules that require specific dependencies.
